import Foundation

nonisolated struct CaptionTrack: Hashable, Identifiable, Sendable {
    let id: String
    let baseURL: URL
    let languageCode: String
    let displayName: String
    let isAutoGenerated: Bool
}

nonisolated struct CaptionCue: Hashable, Identifiable, Sendable {
    let id: Int
    let startTime: TimeInterval
    let endTime: TimeInterval
    let text: String

    func contains(_ time: TimeInterval) -> Bool {
        time >= startTime && time < endTime
    }
}

nonisolated struct PlayerCaptionTrack: Decodable, Sendable {
    let baseURL: URL
    let languageCode: String
    let name: CaptionTrackName?
    let kind: String?
    let vssID: String?

    var captionTrack: CaptionTrack {
        CaptionTrack(
            id: vssID ?? "\(languageCode)-\(baseURL.absoluteString)",
            baseURL: baseURL,
            languageCode: languageCode,
            displayName: name?.displayName ?? languageCode,
            isAutoGenerated: kind == "asr"
        )
    }

    private enum CodingKeys: String, CodingKey {
        case baseURL = "baseUrl"
        case languageCode
        case name
        case kind
        case vssID = "vssId"
    }
}

nonisolated struct CaptionTrackName: Decodable, Sendable {
    let simpleText: String?
    let runs: [CaptionTrackNameRun]?

    var displayName: String? {
        if let simpleText, !simpleText.isEmpty {
            return simpleText
        }

        let runText = runs?
            .map(\.text)
            .joined()
            .trimmingCharacters(in: .whitespacesAndNewlines)

        return runText?.isEmpty == false ? runText : nil
    }
}

nonisolated struct CaptionTrackNameRun: Decodable, Sendable {
    let text: String
}

nonisolated struct PlayerCaptionResponse: Decodable, Sendable {
    let captions: PlayerCaptions?

    var captionTracks: [CaptionTrack] {
        captions?.playerCaptionsTracklistRenderer?.captionTracks.map(\.captionTrack) ?? []
    }
}

nonisolated struct PlayerCaptions: Decodable, Sendable {
    let playerCaptionsTracklistRenderer: PlayerCaptionsTracklistRenderer?
}

nonisolated struct PlayerCaptionsTracklistRenderer: Decodable, Sendable {
    let captionTracks: [PlayerCaptionTrack]
}
